name: green_life_app
description: Green Life App
publish_to: 'none'

version: 1.0.3+3

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  ## State Management
  flutter_riverpod: ^2.3.6

  ## UI
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  syncfusion_flutter_datepicker: ^22.1.37
  month_picker_dialog: ^2.0.2

  ## Firebase
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  cloud_functions: ^4.5.1
  firebase_crashlytics: ^3.4.1

  ## Social Login
  kakao_flutter_sdk_user: ^1.6.1
  google_sign_in: ^6.1.5
  flutter_naver_login: ^1.8.0
  sign_in_with_apple: ^5.0.0

  ## Network
  dio: ^5.3.3

  ## Utils
  logger: ^1.4.0
  flutter_dotenv: ^5.1.0
  clipboard: ^0.1.3
  url_launcher: ^6.1.14
  package_info_plus: ^4.0.2
  flutter_localizations:
    sdk: flutter

  ## Object
  equatable: ^2.0.5
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0

  ## Storage
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.5
  very_good_analysis: ^5.0.0+1
  json_serializable: ^6.7.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21


flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - shorebird.yaml

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 700
    - family: GmarketSans
      fonts:
        - asset: assets/fonts/GmarketSans/GmarketSansLight.otf
          weight: 300
        - asset: assets/fonts/GmarketSans/GmarketSansMedium.otf
          weight: 500
        - asset: assets/fonts/GmarketSans/GmarketSansBold.otf
          weight: 700
flutter_gen:
  colors:
    inputs:
      - assets/color/colors.xml
